openapi: 3.0.0
info:
  title: かんたん株価試算 API
  description: リクエストにはクライアントIDとクライアントシークレットを用いたがJWT認証が必要です
  version: 1.0.0
servers:
  - url: https://kantankabuka-external-api-722937962589.asia-northeast1.run.app/v1
    description: Tendems
  - url: https://external-api-tandems.kantankabuka.com/v1
    description: Tendems
  - url: http://localhost:8080/v1
    description: Local server
security:
  - BearerAuth: [] # 全体にJWT認証を要求する設定
paths:
  /check_required_prev3:
    post:
      summary: 株価試算に前三期分のデータが必要かの確認
      parameters:
        - $ref: '#/components/parameters/Content-Type'
        - $ref: '#/components/parameters/Kantankabuka-Client-ID'
      requestBody:
        $ref: '#/components/requestBodies/body_check_required_prev3'
      responses:
        '200':
          $ref: '#/components/responses/response200_check_required_prev3'
        '400':
          $ref: '#/components/responses/response400'
        '401':
          $ref: '#/components/responses/response401'
        '500':
          $ref: '#/components/responses/response500'
  /calculation:
    post:
      summary: 株価試算
      parameters:
        - $ref: '#/components/parameters/Content-Type'
        - $ref: '#/components/parameters/Kantankabuka-Client-ID'
      requestBody:
        $ref: '#/components/requestBodies/body_calculation'
      responses:
        '200':
          $ref: '#/components/responses/response200_calculation'
        '400':
          $ref: '#/components/responses/response400'
        '401':
          $ref: '#/components/responses/response401'
        '500':
          $ref: '#/components/responses/response500'
  /transition:
    post:
      summary: 株価推移
      parameters:
        - $ref: '#/components/parameters/Content-Type'
        - $ref: '#/components/parameters/Kantankabuka-Client-ID'
      requestBody:
        $ref: '#/components/requestBodies/body_transition'
      responses:
        '200':
          $ref: '#/components/responses/response200_transition'
        '400':
          $ref: '#/components/responses/response400'
        '401':
          $ref: '#/components/responses/response401'
        '500':
          $ref: '#/components/responses/response500'
components:
  parameters:
    Content-Type:
      name: Content-Type
      in: header
      required: true
      schema:
        type: string
        default: application/json
    Kantankabuka-Client-ID:
      name: Kantankabuka-Client-ID
      in: header
      required: true
      schema:
        type: string
  requestBodies:
    body_check_required_prev3:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              company:
                $ref: '#/components/schemas/company'
              settlements:
                type: array
                items:
                  $ref: '#/components/schemas/settlement'
          examples:
            example1:
              $ref: '#/components/examples/example_check_required_prev3_true'
            example2:
              $ref: '#/components/examples/example_check_required_prev3_false'
    body_calculation:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              company:
                $ref: '#/components/schemas/company'
              settlements:
                type: array
                items:
                  $ref: '#/components/schemas/settlement'
              financial:
                $ref: '#/components/schemas/financial'
              stockHolders:
                type: array
                items:
                  $ref: '#/components/schemas/stockHolderForCaluculationParam'
    body_transition:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              company:
                $ref: '#/components/schemas/company'
              settlements:
                type: array
                items:
                  $ref: '#/components/schemas/settlement'
              financial:
                $ref: '#/components/schemas/financial'
              stockHolders:
                type: array
                items:
                  $ref: '#/components/schemas/stockHolderForTransitionParam'
              future:
                $ref: '#/components/schemas/future'
              calculationResult:
                $ref: '#/components/schemas/calculationResult'
  schemas:
    company:
      type: object
      summary: 会社情報
      properties:
        primaryIndustry:
          type: string
          description: 業種・大分類（別途、早見表を参照してください）
        secondaryIndustry:
          type: string
          description: 業種・中分類（別途、早見表を参照してください）
        tertiaryIndustry:
          type: string
          description: 業種・小分類（別途、早見表を参照してください）
        allStock:
          type: integer
          description: 発行済株式数・全株式
        treasuryStock:
          type: integer
          description: 発行済株式数・自己株式
    settlement:
      type: object
      properties:
        asset:
          type: integer
          description: 資産額（千円）
        debt:
          type: integer
          description: 負債額（千円）
        sales:
          type: integer
          description: 売上額（千円）
        fulltimeNumber:
          type: integer
          description: 従業員数（正社員）
        parttimeNumber:
          type: integer
          description: 従業員数（パート）
        dividend:
          type: integer
          description: 配当支払い額（千円）
        income:
          type: integer
          description: 課税所得（千円）
        lossDeduction:
          type: integer
          description: 繰越欠損金の控除額（千円）
        capital:
          type: integer
          description: 資本金等の額（千円）
        profitReserve:
          type: integer
          description: 利益積立金額（千円）
    financial:
      type: object
      properties:
        year:
          type: integer
          description: 決算期の年
        month:
          type: integer
          description: 決算期の月
    stockHolderForCaluculationParam:
      type: object
      properties:
        stockNumber:
          type: integer
          description: 株数
        evaluationType:
          type: string
          description: 評価方式（英字）:A,B,C
    stockHolderForCaluculationResponse:
      type: object
      properties:
        stockNumber:
          type: integer
          description: 株数
        stockRate:
          type: number
          description: 株全体比率
        evaluationType:
          type: string
          description: 評価方式（英字）:A,B,C
        evaluationTypeText:
          type: string
          description: 評価方式（日本語単語）：原則（相続税評価額),原則（相続税評価額),特例（配当還元価額）
        amount:
          type: integer
          description: 評価方式に基づいた評価額
    stockHolderForTransitionParam:
      type: object
      properties:
        stockNumber:
          type: integer
          description: 株数
    stockHolderForTransitionResponse:
      type: object
      properties:
        amount:
          type: integer
          description: 評価方式に基づいた評価額
    future:
      type: object
      properties:
        incomes:
          type: array
          items:
            type: integer
        measures:
          type: array
          items:
            type: integer
    calculationResult:
      type: object
      properties:
        stockOne:
          type: integer
          description: 株価（千円）
        stockAll:
          type: integer
          description: 株価（千円）
  responses:
    response200_check_required_prev3:
      description: check_required_prev3の正常系レスポンスです。
      content:
        application/json:
          schema:
            type: boolean
    response200_calculation:
      description: calculationの正常系レスポンスです。
      content:
        application/json:
          schema:
            type: object
            properties:
              stockOne:
                type: number
                example: 5000
              stockAll:
                type: number
          example: 100000
          examples:
            example1:
              $ref: '#/components/examples/response_example1'
            example2:
              $ref: '#/components/examples/response_example2'
    response200_transition:
      description: transitionの正常系レスポンスです。
      content:
        application/json:
          schema:
            type: object
            properties:
              companyScales:
                type: array
                items:
                  type: string
                example: ['A', 'B', 'C']
              netAssetValues:
                type: array
                items:
                  type: number
                  example: [0.0, 0.0, 0.0]
          examples:
            example1:
              $ref: '#/components/examples/response_example1'
            example2:
              $ref: '#/components/examples/response_example2'
    response400:
      description: 入力値のエラーや違反です。具体的なパラメータに言及します。
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: 'invalid primaryIndustry'
    response401:
      description: 認証のエラーや違反です。一律「invalid authentication」を返却します。
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: 'invalid primaryIndustry'
    response500:
      description: API内部のエラーです。一律「internal server error」を返却します。
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: 'internal server error'
    error401:
      type: object
      properties:
        error:
          type: string
          description:
    error500:
      type: object
      properties:
        error:
          type: string
          description: サーバー内部のエラーです。一律「internal server error」を返却します。
  examples:
    example_check_required_prev3_true:
      summary: 前三期分のデータが必要
      value:
        company:
          primaryIndustry: 'K'
          secondaryIndustry: '69'
          tertiaryIndustry: ''
          allStock: 10000
          treasuryStock: 0
          isFoundedRecently: false
          isGoingClose: false
          isOverHalfStock: false
        settlements:
          [
            {
              asset: 30000,
              debt: 10000,
              sales: 50000,
              fulltimeNumber: 0,
              parttimeNumber: 0,
              dividend: 0,
              income: 0,
              lossDeduction: 0,
              capital: 1000,
              profitReserve: 0,
            },
            {
              asset: 30000,
              debt: 10000,
              sales: 50000,
              fulltimeNumber: 0,
              parttimeNumber: 0,
              dividend: 0,
              income: 0,
              lossDeduction: 0,
              capital: 1000,
              profitReserve: 0,
            },
            {
              asset: 30000,
              debt: 10000,
              sales: 50000,
              fulltimeNumber: 0,
              parttimeNumber: 0,
              dividend: 0,
              income: 0,
              lossDeduction: 0,
              capital: 1000,
              profitReserve: 0,
            },
          ]
    example_check_required_prev3_false:
      summary: 前三期分のデータが必要ではない
      value:
        company:
          primaryIndustry: 'K'
          secondaryIndustry: '69'
          tertiaryIndustry: ''
          allStock: 10000
          treasuryStock: 0
          isFoundedRecently: false
          isGoingClose: false
          isOverHalfStock: false
        settlements:
          [
            {
              asset: 80000,
              debt: 30000,
              sales: 100000,
              fulltimeNumber: 20,
              parttimeNumber: 0,
              dividend: 0,
              income: 10000,
              lossDeduction: 0,
              capital: 1000,
              profitReserve: 268375,
            },
            {
              asset: 80000,
              debt: 30000,
              sales: 100000,
              fulltimeNumber: 20,
              parttimeNumber: 0,
              dividend: 1000,
              income: 10000,
              lossDeduction: 0,
              capital: 1000,
              profitReserve: 268375,
            },
            {
              asset: 80000,
              debt: 30000,
              sales: 100000,
              fulltimeNumber: 20,
              parttimeNumber: 0,
              dividend: 1000,
              income: 10000,
              lossDeduction: 1000,
              capital: 1000,
              profitReserve: 0,
            },
          ]
    response_example1:
      summary: 前三期分のデータが必要
      value:
        result: true
    response_example2:
      summary: 前三期分のデータが必要ではない
      value:
        result: false
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT # 表示にJWTを指定
